<div id="$fullId$" class="answer $fullId$ $answerType$">
<table><tr><td>
<div id="f_$fullId$-t" class="title $fullId$-t">$AnswerTitleTooltip()$</div>
	$text$ 
</td><td>
	<input id="f_$fullId$_1" name="group-$fullId$" type="radio" /> ja
	<input id="f_$fullId$_2" name="group-$fullId$" type="radio" /> nein
	<input id="f_$fullId$_3" name="group-$fullId$" type="radio" /> unbekannt
</tr></table>	
</div>