body,table,div {
	font-size: 10pt;
}

body {
	overflow: auto;
}

#content {
	width: 74%;
}
	
#dialog-content{	
	height: auto;
	overflow: visible;
}

.question-content {
	padding: 2px 1px 4px 1px;
}

.question .title {
	padding-left: 0px;
}

.ok-button {
	border: 1px solid #ccc;
	text-align: center;
	cursor: pointer;
	-moz-box-shadow: 0px 0px 0px #888;
	-webkit-box-shadow: 0px 0px 0px #888;
	box-shadow: 0px 0px 0px #888;
	margin-right: 3px;
	height: 100%;
	font-size: 6pt;
}

#head {
	height: auto;
}

.question, .question-c {
	border: 1px solid grey;
}

#right {
	padding: 14px;
}

#head, .questionnaire-content, 
.questionnaire > .title, .questionnaire > .title td,
#x_questionnairenav, #right {
	background-color: #f3faff;
	background-image: none;
}

/* save vertical space between the answers */
.answer {
	margin: -2px 2px;
}