<div id="$elementID$_popup" class="explanationPopup">
    <div id="$elementID$_popupContent" class="explanationPopupContent">      
        <b class="sol" style="color:$color$">$sol_name$</b> - $rating$<br />
        <div class="details">space for more details</div>
        $content$
    </div>
    <br />
    <div id="popupCloser" onclick="explanationPopupHandle('$elementID$');" class="linkstyle">
        Close Explanation    
    </div>
</div>




