#left {
	width: 30%;
}


#right {
	width: 20%;
}

#content {
	width: 47%;
	margin: 0px 1% 0px 0px;
}

#navigation > .title {
	background-color: #bbf;
	min-height: 15px;
}

#head {
    background-image: none;
	background-color: #f8f8f8;
	height: 5%;
}

#navigation-list {
	background-color: #f8f8f8;
}

.question-content {	padding: 2px 50px 20px 50px; }

#head, .questionnaire-content, 
.questionnaire > .title, .questionnaire > .title td,
#x_questionnairenav, #right {
	background-color: #f3faff;
	background-image: none;
}

/* save vertical space between the answers */
.answer {
	margin: -2px 2px;
}