<div id="jqConfirmDialog" title="ACHTUNG!">
		<div style="float:left;" id="numberUnanswered"></div> 
		<div style="float:left; margin-left:5px;">unbeantwortete Fragen!</div><br />
		<div> Den aktuellen Fall trotzdem speichern? Dann bitte den
		gewünschten Dateinamen angeben und "SPEICHERN" klicken.</div>
		<div style="margin-top:2px;">
			<input id="confirmFilename"/>
		</div> 	
		<div style="margin-top:2px;" id="confirmError"></div>
</div>