<div class="parent" $if(indent)$style="margin-left: $indent$px;"$endif$>
	$content$
	<div class="child">
		<table border="0" cellpadding="2" cellspacing="2">
		<tr><td><b>VirtualClassName:</b></td><td>$vcn$</td></tr>
		<tr><td><b>Parser:</b></td><td>$parser$</td></tr>
		<tr><td><b>Interne Klasse:</b></td><td>$internal$</td></tr>
		<tr><td><b>Renderer:</b></td><td>$renderer$</td></tr>
		<tr><td valign="top"><b>HTML-Template:</b></td><td>$html_template$</td></tr>
		</table>
	</div>
</div>