<div style="display: none">
	<div id="jqConfirmEoSDialog" title="
			$if(langEN)$
				End of session confirmation
			$endif$ 
			$if (langDE)$
                                Ende der Eingabesitzung
		    $endif$
			">
                        <p> 
                        $if(langEN)$
				All questions are answered now. <br /><br />
                                If you wish
                                to end the current input session - for example, 
                                to start entering a new case afterwards - please    
                                hit the <b>Yes, end session</b> button. <br />
                                Otherwise -
                                if you would like to correct one ore more values -
                                please hit the <b>No, go on</b> button.
			$endif$ 
			$if (langDE)$
                                Sie haben nun alle Fragen beantwortet. <br /><br />Falls Sie
                                die aktuelle Eingabesitzung nun beenden möchten -
                                z.B. um anschließend einen neuen Fall zu starten - 
                                klicken Sie bitte auf <b>Ja, Session beenden</b>.<br />
                                Andernfalls - falls sie einen oder mehrere Werte
                                nochmals anpassen möchten - klicken Sie bitte auf
                                <b>Nein, Eingabe fortsetzen</b>
		    $endif$
                        </p>
	</div>
</div>