<div id="jqFFDialog" class="feedbackform" title="Feedback">

    <div id="ffexplanation" class="margBott"> 
    Bitte tragen Sie ihre Bemerkungen, Fragen, oder Wünsche in das Feedback-Feld    
    ein. 
    Name und EMail sind dabei optional, falls Sie aber eine Frage senden und eine
    Antwort erhalten wollen, füllen Sie diese Felder bitte aus. Andernfalls können Sie 
    das Feedback anonym schicken (Name und EMail leer lassen).
    </div>
    <div id="ffmessage"> </div>

    <table>
    <tbody>
        <tr>
            <td width="60px;">Feedback:</td>
            <td><textarea id="fffeedback" class="longTextarea"></textarea></td> 
	</tr>
        <tr>
            <td width="60px;">Name:</td>
            <td><input id="ffname" class="longTextfield"/></td> 
	</tr>
	<tr>
		<td width="60px;">EMail:</td>
		<td><input id="ffmail" class="longTextfield"/></td> 
	</tr>
    </tbody>
    </table>
</div>