<div id="jqFFDialog" class="feedbackform" title="Feedback">

    <div id="ffexplanation"> 
    For sending us your feedback, please fill in the fields below. 
    Name and EMail are optional, but may be useful in case you sent us a question
    or would like us to respond to you directly.
    Otherwise, the feedback can as well be sent anonymously.
    </div>
    <div id="ffmessage"> </div>

    <table>
    <tbody>
        <tr>
            <td width="60px;">Name:</td>
            <td><input id="ffname" /></td> 
	</tr>
	<tr>
		<td width="60px;">EMail:</td>
		<td><input id="ffmail" /></td> 
	</tr>
        <tr>
            <td width="60px;">Feedback:</td>
            <td><textarea id="fffeedback" cols="30" rows="3"></textarea></td> 
	</tr>
					
    </tbody>
    </table>
</div>