<div style="display:none">
<div id="jqLoadCaseDialog" class="table"
	title="$if(langEN)$
				Load case
			$endif$ 
			$if (langDE)$
		    	Fall laden
		    $endif$">
	<div id="fileselectList" class="row">	    
	<select id="caseSelect" name="files" size="12">
	    $fileselectopts$ 
        </select>
	</div>	
        <div id="clearnameLabel" class="row fileClearnameLabel">OR enter Clearname:</div>
	<div id="clearnameInput" class="row">
	    <input name="fileClearname" class ="fileClearname" size="41">
        </div>
</div>
</div>