<div style="display:none">
<div id="jqLoadCaseDialog"
	title="$if(langEN)$
				Load case
			$endif$ 
			$if (langDE)$
		    	Fall laden
		    $endif$">
	<select id="caseSelect" name="files" size="12" style="width:300px;">
    	$fileselectopts$ 
        </select>
        <div class="fileClearnameLabel">OR enter Clearname:</div>
        <input name="fileClearname" class = "fileClearname" size="41">
        
</div>
</div>