
		<td>
			<img id="lang_en" src="kbimg/enFlag.png" alt="english" width="30px" />
		</td>
		<td style="padding-left:12px;">
			<img id="lang_fr" src="kbimg/frFlag.png" alt="français" width="30px" />
		</td>
		<td style="padding-left:12px;">
			<img id="lang_it" src="kbimg/itFlag.png" alt="italiano" width="30px" />
		</td>
		<td style="padding-left:12px;">
			<img id="lang_de" src="kbimg/deFlag.png" alt="deutsch" width="30px"/>
		</td>
		<td style="padding-left:12px;">
			<img id="lang_es" src="kbimg/esFlag.png" alt="español" width="30px" />
		</td>
		<td style="padding-left:12px;">
			<img id="lang_pl" src="kbimg/plFlag.png" alt="polski" width="30px" />
		</td>
		<td style="padding-left:25px;" rowspan="2">
			$Logo()$
		</td>