
<table>
	<tbody>
	<tr>
		<td style="padding-left:10px;">
			<img src="kbimg/enFlag.png" alt="english" width="30px" />
		</td>
		<td style="padding-left:10px;">
			<img src="kbimg/deFlag.png" alt="deutsch" width="30px" />
		</td>
		<td style="padding-left:10px;">
			<img src="kbimg/frFlag.png" alt="français" width="30px" />
		</td>
		<td style="padding-left:10px;">
			<img src="kbimg/esFlag.png" alt="español" width="30px" />
		</td>
		<td style="padding-left:10px;">
			<img src="kbimg/itFlag.png" alt="italiano" width="30px" />
		</td>
		<td style="padding-left:10px;">
			<img src="kbimg/plFlag.png" alt="polski" width="30px" />
		</td>
		<td style="padding-left:20px;">
			$Logo()$
		</td>
	</tr>
	</tbody>
</table>
