<table>
	<tbody>
	<tr>
		<td>
			<img src="kbimg/enFlag.png" alt="english" width="30px" 
                        onclick="toggle_language(2)"/>
		</td>
		<td style="padding-left:12px;">
			<img src="kbimg/frFlag.png" alt="français" width="30px" 
                           onclick="toggle_language(5)"/>
		</td>
		<td style="padding-left:12px;">
			<img src="kbimg/itFlag.png" alt="italiano" width="30px" 
                        onclick="toggle_language(4)"/>
		</td>
		<td style="padding-left:12px;">
			<img src="kbimg/deFlag.png" alt="deutsch" width="30px" 
                           onclick="toggle_language(1)"/>
		</td>
		<td style="padding-left:12px;">
			<img src="kbimg/esFlag.png" alt="español" width="30px" 
                        onclick="toggle_language(3)"/>
		</td>
		<td style="padding-left:12px;">
			<img src="kbimg/plFlag.png" alt="polski" width="30px" 
                        onclick="toggle_language(6)"/>
		</td>
		<td style="padding-left:25px;" rowspan="2">
			$Logo()$
		</td>
	</tr>
	<tr>
		<td colspan="6">$info$</td>
	</tr>
	<tr>
		
	</tr>
	</tbody>
</table>
