<div style="display: none">
	<div id="jqConfirmDialog" title="
			$if(langEN)$
				Save current file
			$endif$ 
			$if (langDE)$
		    	Aktuellen Fall speichern
		    $endif$
			"> 	
			<div style="margin-top:5px;" id="confirmMessage">
			$if(langEN)$
				Please choose a file name.
			$endif$ 
			$if (langDE)$
		    	Bitte wählen sie einen Dateinamen.
		    $endif$
			</div>
			<div style="margin-top:5px;">
				<input id="confirmFilename"/>
			</div>
	</div>
</div>