<div style="display:none">
	<div id="jqSummaryDialog" title="$if(langEN)$Summary$endif$$if (langDE)$Zusammenfassung$endif$">
		<ul>
			<li><a href="#gridSummary">Grid Summary</a></li>
                        <li><a href="#Level1QuestionnaireSummary">Level 1 Summary</a></li>
			<li><a href="#questionnaireSummary">Complete Summary</a></li>
		</ul>
		
                <div style="float:left;" id="gridSummary"> 
			<div id="gridSummaryContent"> 
			</div>
		</div>
		
                <div style="float:left;" id="Level1QuestionnaireSummary">
			<div id="level1SummaryContent">
			</div>
		</div>

                <div style="float:left;" id="questionnaireSummary">
			<div id="questionnaireSummaryContent">
			</div>
		</div>
	</div>
</div>