<table class="tableNoTopMargin">
    <tbody>
        <tr>
            <td></td>
            <td><div id="ueqMessage"> </div></td>
            <td>$UE_ScaleEmpty7_GER()$</td> 
	</tr>
        <tr>
            <td class="topText">1</td>
            <td class="leftPadd topText" >Ich empfand die Interaktion mit dem System insgesamt als intuitiv.   </td>
            <td>$UE_ScaleLikert7(id="UE_Ich_empfand_die_Interaktion_mit_dem_System_insgesamt_als_intuitiv.   ")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText">2</td>
            <td class="leftPadd topText">Ich konnte die (Re-)Aktionen des Systems immer gut nachvollziehen.</td>
            <td>$UE_ScaleLikert7(id="UE_Ich_konnte_die_(Re-)Aktionen_des_Systems_immer_gut_nachvollziehen.")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText">3</td>
            <td class="leftPadd topText"> Ich habe mich bei der Benutzung des Systems sehr souverän gefühlt.</td>
            <td>$UE_ScaleLikert7(id="UE_Ich_habe_mich_bei_der_Benutzung_des_Systems_sehr_souverän_gefühlt.")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText">4</td>
            <td class="leftPadd topText">Ich konnte nachvollziehen, warum das System zu der finalen Bewertung des Sachverhalts kam.</td>
            <td>$UE_ScaleLikert7(id="UE_Ich_konnte_nachvollziehen,_warum_das_System_zu_der_finalen_Bewertung_des_Sachverhalts_kam.")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText">5</td>
            <td class="leftPadd topText">Ich habe das Gefühl, durch die Benutzung des Systems zusätzliches Wissen bezüglich des Sachverhalts gewonnen zu haben.</td>
            <td>$UE_ScaleLikert7(id="UE_Ich_habe_das_Gefühl,_durch_die_Benutzung_des_Systems_zusätzliches_Wissen_bezüglich_des_Sachverhalts_gewonnen_zu_haben.")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText">6</td>
            <td class="leftPadd topText">Ich denke, die meisten Nutzer könnten schnell lernen, dieses System zu nutzen.</td>
            <td>$UE_ScaleLikert7(id="UE_Ich_denke,_die_meisten_Nutzer_könnten_schnell_lernen,_dieses_System_zu_nutzen.")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText">7</td>
            <td class="leftPadd topText">Ich würde das System auch zukünftig für die Klärung ähnlicher Sachverhalte nutzen.</td>
            <td>$UE_ScaleLikert7(id="UE_Ich_würde_das_System_auch_zukünftig_für_die_Klärung_ähnlicher_Sachverhalte_nutzen.")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
	<tr>
            <td class="topText">8</td>
            <td class="topText leftPadd">Weitere Anmerkungen:</td>
            <td><textarea id="UE_QFreeFeedback" class="longTextarea"></textarea></td> 
	</tr>
					
    </tbody>
</table>