<table>
    <tbody>
        <tr>
            <td></td>
            <td><div id="ueqMessage"> </div></td>
            <td>$UE_ScaleEmpty5_GER()$</td> 
	</tr>
        <tr>
            <td>1</td>
            <td>Das System war insgesamt einfach zu bedienen</td>
            <td>$UE_ScaleLikert5(id="UE_Das_System_war_insgesamt_einfach_zu_bedienen")$</td> 
	</tr>
	
					
    </tbody>
</table>