<table class="tableNoTopMargin">
    <tbody>
        <tr>
            <td></td>
            <td class="width40Percent"><div id="ueqMessage"> </div></td>
            <td>$UE_ScaleEmpty7_GER()$</td> 
	</tr>
        <tr>
            <td class="topText fontOnePointTwo">1</td>
            <td class="leftPadd topText fontOnePointTwo width40Percent" >Ich empfand die Interaktion mit dem System insgesamt als intuitiv.   </td>
            <td>$UE_ScaleLikert7(id="UE_Ich_empfand_die_Interaktion_mit_dem_System_insgesamt_als_intuitiv.   ")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText fontOnePointTwo">2</td>
            <td class="leftPadd topText fontOnePointTwo width40Percent">Ich empfand die inhaltliche Strukturierung der Fragen als verständlich.</td>
            <td>$UE_ScaleLikert7(id="UE_Ich_empfand_die_inhaltliche_Strukturierung_der_Fragen_als_verständlich.")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText fontOnePointTwo">3</td>
            <td class="leftPadd topText fontOnePointTwo width40Percent">Ich konnte nachvollziehen, warum das System zu der finalen Bewertung des Sachverhalts kam.</td>
            <td>$UE_ScaleLikert7(id="UE_Ich_konnte_nachvollziehen,_warum_das_System_zu_der_finalen_Bewertung_des_Sachverhalts_kam.")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText fontOnePointTwo">4</td>
            <td class="leftPadd topText fontOnePointTwo width40Percent">Ich denke, ich konnte mithilfe des Systems den Sachverhalt zutreffend einschätzen/lösen.</td>
            <td>$UE_ScaleLikert7(id="UE_Ich_denke,_ich_konnte_mithilfe_des_Systems_den_Sachverhalt_korrekt_einschätzen/lösen.")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText fontOnePointTwo">5</td>
            <td class="leftPadd topText fontOnePointTwo width50Percent">Ich habe das Gefühl, durch die Benutzung des Systems zusätzliches Wissen bezüglich des Sachverhalts gewonnen zu haben.</td>
            <td>$UE_ScaleLikert7(id="UE_Ich_habe_das_Gefühl,_durch_die_Benutzung_des_Systems_zusätzliches_Wissen_bezüglich_des_Sachverhalts_gewonnen_zu_haben.")$</td> 
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText fontOnePointTwo">6</td>
            <td class="topText leftPadd fontOnePointTwo width50Percent">Welche der beiden verwendeten Dialoge hat mir besser gefallen? (Nur nach Bearbeitung beider Fälle beantworten!)</td>
            <td>
                <div style="float:left;padding:10px;font-size:8pt;"><input id="UE_QUIRating1" type="radio" name="UE_QUIRating" value="Dialog 1" style="margin-right:10px;">Dialog 1</input></div>
                <div style="float:left;padding:10px;font-size:8pt;"><input id="UE_QUIRating2" type="radio" name="UE_QUIRating" value="Dialog 2" style="margin-right:10px;">Dialog 2</input></div>
                <div style="float:left;padding:10px;font-size:8pt;"><input id="UE_QUIRating3" type="radio" name="UE_QUIRating" value="Beide gleich" style="margin-right:10px;">Beide gleich</input></div>
            </td>
	</tr>
        <tr><td colspan="3"><hr></td></tr>
        <tr>
            <td class="topText fontOnePointTwo">7</td>
            <td class="topText leftPadd fontOnePointTwo width50Percent">Ich bin Jurist und verfüge über juristisches Hintergrundwissen im/in...</td>
            <td>
                <div style="float:left;padding:10px;font-size:8pt;"><input id="UE_QUserCompetence" type="radio" name="UE_QCompetence" value="AR" style="margin-right:5px;">Arbeitsrecht</input></div>
                <div style="float:left;padding:10px;font-size:8pt;"><input id="UE_QUserCompetence" type="radio" name="UE_QCompetence" value="Jurist" style="margin-right:5px;">anderen Rechtsgebieten</input></div>
                <div style="float:left;padding:10px;font-size:8pt;"><input id="UE_QUserCompetence" type="radio" name="UE_QCompetence" value="NonJurist" style="margin-right:5px;">Ich bin KEIN Jurist</input></div>
             
            </td>
	</tr>
        <tr><td colspan="3"><hr></td></tr>
	<tr>
            <td class="topText fontOnePointTwo">7</td>
            <td class="topText leftPadd fontOnePointTwo">Weitere Anmerkungen:</td>
            <td><textarea id="UE_QFreeFeedback" rows="3" class="longTextarea">z.B.: was hat mir gut gefallen, was hat mir nicht gefallen, sind Probleme aufgetreten (technische, bez. der Interaktion oder Verständnis)...</textarea></td> 
	</tr>
					
    </tbody>
</table>