<table>
    <tbody>
        <tr>
            <td><input id=$id$ type="radio" name="uelikert5_$id$" value="1">1</></td>
            <td><input id=$id$ type="radio" name="uelikert5_$id$" value="2">2</></td>
            <td><input id=$id$ type="radio" name="uelikert5_$id$" value="3">3</></td>
            <td><input id=$id$ type="radio" name="uelikert5_$id$" value="4">4</></td>
            <td><input id=$id$ type="radio" name="uelikert5_$id$" value="5">5</></td>
            </tr>				
    </tbody>
</table>