<table class="tableNoTopMargin">
    <tbody>
        <tr>
            <td><input id=$id$ type="radio" name="uelikert7_$id$" value="0"> </></td>
            <td><input id=$id$ type="radio" name="uelikert7_$id$" value="1"> </></td>
            <td><input id=$id$ type="radio" name="uelikert7_$id$" value="2"> </></td>
            <td><input id=$id$ type="radio" name="uelikert7_$id$" value="3"> </></td>
            <td><input id=$id$ type="radio" name="uelikert7_$id$" value="4"> </></td>
            <td><input id=$id$ type="radio" name="uelikert7_$id$" value="5"> </></td>
            <td><input id=$id$ type="radio" name="uelikert7_$id$" value="6"> </></td>
            </tr>				
    </tbody>
</table>