<div id="jqUEQDialog" class="uequestionnaire" title="Survey">

    <div id="ueqexplanation" class="margBott"> 
    For further improvement of the software, please fill in the following
    questions:
    </div>

    <div id="ueq">
        $UE_SUS()$
    </div>

    <div id="ueqOptional" class="margBott">
    Please provide your name and mail-adress optionally. 
    Otherwise, the feedback can as well be sent anonymously.
    <div>
    
    <table>
    <tbody>
        <tr>
            <td width="60px;">Name:</td>
            <td><input id="ueqname" class="longTextfield" /></td> 
	</tr>
	<tr>
		<td width="60px;">EMail:</td>
		<td><input id="ueqmail" class="longTextfield" /></td> 
	</tr>
    </tbody>
    </table>
    
</div>