$basis()$

$standardLeft()$

#left { -moz-box-shadow: none; -webkit-box-shadow: none; box-shadow: none;
	    margin-top: 1%; }

body,table,div { padding: 0px; margin: 0px; font-family: Arial; font-size: 11pt; text-color: black; }

#topline{ padding: 5px; background-color: rgba(224, 238, 238, 0.5); } 

.question { clear: left; }

.group .title { padding: 10px; font-weight: bold; background-color: rgba(224, 238, 238, 0.5); 
				-moz-border-radius: 5px; -webkit-border-radius: 5px; font-size: 1.25em; }

.question .title { padding: 10px; font-weight: bolder; background: transparent; font-size: 1.0em; }

.question-c .title-c { background-color: #ffffcc; }

.question-d .title-d { background-color: #ddd; }

.tooltip { z-index: 100; background-color: rgba(255, 215, 0, 0.825); padding: 5px;
	-moz-border-radius-bottomright: 5px; -webkit-border-bottom-right-radius: 5px;
	-moz-box-shadow: 3px 3px 3px #888; -webkit-box-shadow: 3px 3px 3px #888;
	font-weight: normal; }

.group { padding-left: 20px; background: transparent url(images/arrow.gif) no-repeat top left; }

.group-content { margin-top: 5px; }

.question-content { float: left; padding: 0px 5px; }

.answer { float: left; margin-right: 2px; }

.selected { border: 3px solid #bbb; padding: 2px; -moz-border-radius: 5px; -webkit-border-radius: 5px; margin-top: 1px;}

.not-selected { padding: 2px; border: 3px solid white; -moz-border-radius: 5px; -webkit-border-radius: 5px; margin-top: 1px;}

input[type=text] { border: 1px dashed black; }

#head{ font-size: 2em; font-variant: small-caps; text-align: center; background: #e7e7e7;
	background-image: none; padding: 5px; }

td { vertical-align: top; }

#solutiontop{ position: relative; float: left; font-weight: bold; font-size: 1.75em;
		   	  width: 25%; padding: 15px; }

#solutiontoprating{ position: relative;	float: left; font-size: 1.25em;
                    font-weight: bold; border: 3px solid rgba(154, 205, 50, 0.525); padding: 15px;
                    -moz-border-radius: 5px; -webkit-border-radius: 5px; vertical-align: middle; }

#topinfo { clear: left; padding: 15px; height: 150px; background-color: rgb(255, 248, 220); 
		   -moz-border-radius: 5px; -webkit-border-radius: 5px; margin-top: 5px; margin-bottom: 5px;}

#content { float: left;	width: 70%;	margin: 0px 1% 0px 1%; }

#dialog-content { margin-bottom: 15px; }