$basis()$

body,table,div {
	padding: 0px;
	margin: 0px;
	font-family: Arial;
	font-size: 11pt;
	text-color: black;
}

.question {
	border: 2px solid gray;
	padding: 2px;
	margin: 5px;
}

.question-c {
	border: 3px solid gray;
}

.question-d {
	border: 1px solid gray;
}

.page {
	border: 1px solid red;
}

.answer {
	border: 1px solid green;
}

.tooltip {
	z-index: 100;
	background-color: white;
	padding: 5px;
	border: 1px solid black;
	font-weight: normal;
}

.title {
	padding-left: 4px;
	padding-right: 4px;
	vertical-align: middle;
	font-weight: bolder;
	border: 1px solid orange;
}