/**
* General basic CSS statements for the DocLoad Module
*
* @author	Martina Freiberg
*/



.row{display: table-row;}

.cell{display: table-cell; }

.labelcellFirstRow{margin-top:-20px;}

.labelcell{font-family: fantasy;
    font-size: 1.1em;
    font-weight: bold;
    padding-bottom: 10px;
    padding-top: 20px;}

.selectcell{min-width: 200px; padding: 5px; align: center; vertical-align: middle;}

.firstcell{background: white; -moz-border-radius: 15px 0px 0px 15px; 
    border-radius: 15px 0px 0px 15px; border: 2px solid white;}

.lastcell{background: white; -moz-border-radius: 0px 15px 15px 0px; 
    border-radius: 0px 15px 15px 0px; border: 2px solid white;}

.buttoncell{min-width: 50px; padding: 5px;}

#docloadKBName{color:#777777; font-weight: bold; 
    padding: 5px; padding-left:15px;}

#docloader{display: table; background-color:	#f5f5f5; padding: 10px; 
    -moz-border-radius: 15px; border-radius: 15px; border: 2px solid  	#f5f5f5;}

input{border: 1px dotted darkgrey;
    border-radius: 5px 5px 5px 5px;
    height: 20px;
    width: 240px;
    padding-left: 5px;}

.imgButtonQuad img{margin-bottom: -5px; width: 50px; height: 50px;}

.spacerow{height: 10px;}

.baseDTBrowser{margin-left:10px; }

.baseDTBrowser select{font-family: Verdana; height: 30px; min-height:30px;
    padding-top:5px; padding-left: 10px; min-width: 250px; line-height: 30px;}

.baseDomainBrowser{margin-left:10px;}

.baseFileBrowser{margin-left:10px; position: relative;}

.baseDomainBrowser input{width:240px;}

.button{height: 24px;
    left: 220px;
    min-width: 25px;
    position: absolute;
    top: -1px;}

#docfilename{left: -1px;
    min-width: 220px;
    position: absolute;
    top: -1px;}

#docfileinputorig{opacity: 0;
    position: relative;
    z-index: 2;}

#docfilebutton{width:30px;}

.opacityCell{opacity: 0; position: absolute; z-index: 2;
    height: 50px;
    left: 368px;
    position: absolute;
    top: 85px;
    width: 50px;}