/**
* General basic CSS statements for the DocLoad Module
*
* @author	Martina Freiberg
*/



.row{display: table-row;}

.cell{display: table-cell; }

.labelcell{padding-bottom: 10px; padding-top:20px;}

.selectcell{min-width: 200px; padding: 5px; align: center; vertical-align: middle;}

.firstcell{background: white; -moz-border-radius: 15px 0px 0px 15px; 
    border-radius: 15px 0px 0px 15px; border: 2px solid white;}

.lastcell{background: white; -moz-border-radius: 0px 15px 15px 0px; 
    border-radius: 0px 15px 15px 0px; border: 2px solid white;}

.buttoncell{min-width: 50px; padding: 5px;}

#docloadKBName{font-color: red; color:red; font-weight: bold; padding: 5px; padding-left:10px;}

#docloader{display: table; background-color:	#f5f5f5; padding: 10px; 
    -moz-border-radius: 15px; border-radius: 15px; border: 2px solid  	#f5f5f5;}

input{border: 1px dotted #DDDDDD;
    border-radius: 5px 5px 5px 5px;
    height: 20px;
    min-width: 180px;
    padding-left: 5px;}

.imgButtonQuad img{margin-bottom: -5px; width: 50px; height: 50px;}

.spacerow{height: 10px;}

