$basis()$

body,table,div {
	padding: 0px;
	margin: 0px;
	font-family: Arial;
	font-size: 10pt;
	text-color: black;
}

/* GENERAL question */
.question .title {
	font-size: 11pt;
	background-color: #FEFECC;
	-moz-box-shadow: none;
	-webkit-box-shadow: none;
	box-shadow: none;
}

/* GENERAL question */
.question {
	background-color: #FEFECC;
	padding: 2px;
}


/* CURRENT (active) question */
.question-c .title {
	background-color: #EDFDDD;
}

/* CURRENT (active) question */
.question-c {
	background-color: #EDFDDD;
	padding: 2px;
}

.question-zc, .question-zc .title{
	background-color: #f0f0f0;
	border: none;
}

/* DONE (answered) question */
.question-d .title {
	background-color: #f0f0f0;
}

/* DONE (answered) question */
.question-d {
	background-color: #f0f0f0;
	padding: 2px;
}

.tooltip {
	z-index: 100;
	background-color: rgb(255, 255, 66);
	background-color: rgba(255, 255, 66, 0.925);
	padding: 5px;
	-moz-border-radius-bottomright: 5px;
	-webkit-border-bottom-right-radius: 5px;
	-moz-box-shadow: 3px 3px 3px #888;
	-webkit-box-shadow: 3px 3px 3px #888;
	box-shadow: 3px 3px 3px #888;
	border: 1px solid black;
	font-weight: normal;
}

.title {
	padding-left: 4px;
	padding-right: 4px;
	vertical-align: middle;
	background-color: #e0e0e0;
	-moz-box-shadow: 0 0 5px black;
	-webkit-box-shadow: 0 0 5px black;
	box-shadow: 0 0 5px black;
}

.title,.title td { font-weight: bolder;}

.answer .title {
	background-color: transparent;
	font-size: 10pt;
	font-weight: normal;
	padding: 2px;
}

.answer-zc td {
	background-color: transparent;
	font-size: 10pt;
	font-weight: normal;
	padding: 2px;
}

.yn .title {
	padding: 3px 0px;
}

#head{
	font-size: 1.5em;
	font-variant: small-caps;
	text-align: center;
	background: #DCEDFE;
	background-image: none;
	padding: 5px;
	margin: 5px;
	-moz-box-shadow: 0 0 5px black;
	-webkit-box-shadow: 0 0 5px black;
	box-shadow: 0 0 5px black;
}

body{
	background-color: #F9F9E1;
}

.righttop {
	font-weight: bolder;
 	background:#e7e7e7;
 	padding-top: 2px;
 	padding-bottom: 2px;
 	padding-left: 5px;
}

.rightsub{	
	padding-left:10px;
 	padding-top: 2px;
 	padding-bottom: 2px;
}

#left {
	left: 8px;
	-moz-box-shadow: 0 0 5px black;
	-webkit-box-shadow: 0 0 5px black;
	box-shadow: 0 0 5px black;
	background: #f7f7f7;
	padding:2px;
}

.lefttop { font-weight: bolder; background:#e7e7e7; padding-top: 2px; padding-bottom: 2px; padding-left: 5px; }

.leftsub{ padding-left:10px; padding-top: 2px; padding-bottom: 2px;}

a {	color: blue; }

.ok-button { border: 1px solid #696969; text-align: center; cursor: pointer; 
	background-color: #DDDDDD; font-weight: normal; color: #696969;
	-moz-box-shadow: 0 0 5px black;	-webkit-box-shadow: 0 0 5px black; box-shadow: 0 0 5px black;
}

#content { width: 99%; }

#middle { width: 85%; margin: 0 auto; }

.questionnaire{ -moz-box-shadow: 0 0 5px black;	-webkit-box-shadow: 0 0 5px black; 
 				box-shadow: 0 0 5px black; padding: 5px; background: #FEFECC;}
 				
#questionnaireTitle{ font-weight: bolder; border: 1px dotted solid;}