$basis()$

$legal()$

/* style the num input area of hierarchical num questions */
.floatingnum {line-height: 1.75em; padding: 2px; float: left; margin-right: 15px;}

.floatingnum input { margin-top: -2px; margin-left: 0px;}


/* style the dropdown area of hierarchical oc questions */ 
.floatingCDrop {line-height: 1.5em; padding: 3px; float: left; margin-right: 15px;}

.floatingCDrop select{width: 54px; margin-left: 17px;}

.Dayselect{width: 46px; font-size: 7pt;}

.Monthselect{width: 46px; font-size: 7pt;}

.Yearselect{width: 58px; font-size: 7pt;}

.titleDate{height: 45px; float: left;}

.date-imagebox{float: left; width: 205px;}

.table-imagebox{margin-top: 0px; margin-left: 25px;}

#intro{background-color: white;
    font-family: Arial;
    font-size: 9pt;
    line-height: 1.3em;
    padding: 10px;
    position: fixed;
    top: 80px;
    width: 100%;}


.solution{box-shadow: 0 0 3.5px black;
    clear: both;
    font-size: 1.5em;
    font-weight: bold;
    margin-left: auto;
    margin-right: auto;
    margin-top: 85px;
    padding: 30px 40px 55px;
    width: 65%;}