$basis()$

$legal()$

/* style the num input area of hierarchical num questions */
.floatingnum {line-height: 1.5em; padding: 2px; float: left; margin-right: 15px;}

.floatingnum input {height: 10px; margin-top: -1px; margin-left: 0px;}


/* style the dropdown area of hierarchical oc questions */ 
.floatingCDrop {line-height: 1.5em; padding: 3px; float: left; margin-right: 15px;}

.floatingCDrop select{width: 54px; margin-left: 17px;}

.Dayselect{width: 46px; font-size: 7pt;}

.Monthselect{width: 46px; font-size: 7pt;}

.Yearselect{width: 58px; font-size: 7pt;}

.titleDate{height: 45px; float: left;}

.date-imagebox{float: left; width: 205px;}

.table-imagebox{margin-top: 0px; margin-left: 25px;}