#solutionPanelCell{padding-top: 70px; padding-left: 20px; padding-right: 10px; width: 20%;}

#solutionPanel{background-color: lightslategray; color: white; }

#sol_heading{font-weight: bold; font-size: 1.1em; 
margin-left: 20px;}

.solution{margin-top:5px; margin-left:30px; margin-right: 10px; display: table-row;}

.sol_bgSpacer{background-color: lightslategray; height:20px;}

.solution > img { margin-right: 5px; margin-left:12px; display: table-cell;}

.solutiontext{display: table-cell; vertical-align:middle;}

.solLink{text-decoration: underline; color: blue; cursor: pointer; padding-right: 5px; }

.solText{padding-right: 5px;}

.solScore{}

.bottomSpace{margin-bottom: 10px;}