#solutionPanelCell{padding-top: 70px; padding-left: 20px; padding-right: 10px; width: 20%;}

#solutionPanel{background-color: lightslategray; color: white; width:252px;}

#sol_heading{font-weight: bold; font-size: 1.1em; 
margin-left: 20px;}

.solution{margin-top:5px; margin-left:30px; margin-right: 10px; display: table-row;}

.sol_bgSpacer{background-color: lightslategray; height:20px;}

.solution > img { margin-right: 5px; margin-left:12px; display: table-cell;}


.solText{vertical-align: top;}

.linkstyle{text-decoration: underline; color: blue; cursor: pointer; padding-right: 5px; }

.solScore{vertical-align: top;}


.bottomSpace{margin-bottom: 10px;}

.explanationPopup{background-color:#FFFFFF;
  border:1px solid #999999;
  cursor:default;
  display:none;
  position:absolute;
  text-align:left;
  width:230px;
  z-index:50;
  padding: 10px 10px 10px;
    color: black;
}


.selected{
    display: block;
}