<!DOCTYPE html>
<html>
<head profile="http://www.w3.org/2005/10/profile">
<link rel="icon" type="image/ico" href="images/favicon.ico">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Herzmedizin Dialog - Start</title>
<script src="js/jquery/jquery.min.js" type="text/javascript" language="javascript"></script>
<script src="js/jquery/jquery-ui.custom.min.js" type="text/javascript" language="javascript"></script>

<style type="text/css">
$css$

h1,h2 {
	text-align: center;
	font-family: Verdana, Arial, sans-serif;
}
</style>
</head>
<body>

<h1>$header$</h1>


<p align="center">

<div>$dialog$</div>

</div>
</body>
</html>