<div id="$elementID$_popup" class="explanationPopup" >
    <div id="$elementID$_popupContent_image" class="explanationPopupContent">
        <img id="$id$-popupimg" alt="treemap popupimage" src="$expImagePath$" 
            height="160" width="250" 
            onclick="alert('this is the treemap image');" />
    </div>

    <div id="popupCloser" onclick="explanationPopupHandle('$elementID$');" class="linkstyle">
        Close Explanation    
    </div>
</div>