<div id="sol_$solid$" class="solution">
    <div id="$solid$_row" class="row">
            <div class="cell">
                <img src="$src$" alt="$alt$" title="$tt$" onclick="$click$" width="27"/> 
            </div>
            <div id="$solid$_solText" class="solText cell" onclick="explanationPopupHandle('$solid$');">
                $solutiontext$
            </div>
            <div id="$solid$_solScore" class="solScore cell">
                $scoretext$
            </div>
        </div>
        <div id="popuprow" class="row">
             $explanationpopup$ 
        </div>
</div>