<div id="sol_$solid$" class="solution">
    <img src="$src$" alt="$alt$" title="$tt$" onclick="$click$" width="27"/> 
    <div id="soltext_$solid$" class="solutiontext">
        <div id="$solid$_row" class="row">
        <div id="$solid$_solLink" class="solLink cell" onclick="alert('hurra');">
            $solutiontext$
        </div>
        <div id="$solid$_solScore" class="solScore cell">
            $scoretext$
        </div>
        </div>
    </div>
</div>